services:
  db:
    image: mysql:8.0
    container_name: mysql_clinagenda
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: clinagenda_database   
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-vol:/var/lib/mysql
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password

  flyway:
    image: flyway/flyway:9.22.3
    container_name: flyway_clinagenda
    depends_on:
      - db
    volumes:
      - ./db/migration:/flyway/sql
    command: -url=jdbc:mysql://db:3306/clinagenda_database -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    environment:
      FLYWAY_PLACEHOLDERS_DB: clinagenda_database
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_URL: jdbc:mysql://db:3306/clinagenda_database

volumes:
  db-vol: {}
